### ISSUE TITLE
Support npm commands with selected node version shipped npm

### ISSUE THREAD

**Issue by nicolas-goudry** [ehmicky/nvexeca#4]
**Which problem is this feature request solving?**

I’d like to run an npm command that would use npm version shipped with selected node version.

**Describe the solution you'd like**

From what I understand of your code, I think it should be in `get-node` project, `src/download.js`’s `download` function should return an object containing `nodePath` but also `npmPath`.

Download feature should not strip away `bin/npm`, `bin/npx` and `lib` folders from downloaded archive.

Also, in this project, `src/spawn.js`’s `getCommand` function should add a new `if` testing if command is `npm` and use newly created `npmPath` to run command through execa.

I’m probably missing some things around, but you should get the idea.

**Describe alternatives you've considered**

Use currently installed npm through `execa`, but does require user to have node/npm installed.

**EDIT:** that’s one “small” problem, but a bigger problem is if npm commands run node against an older/newer version than the one installed. Same for tools ran by npm that expects a given node version.

**Can you submit a pull request?**

Maybeee. I guess you would be far more efficient than me on this, as it requires to update several project/dependencies.

**Comment by ehmicky** [comment]
Hi @nicolas-goudry,

Could you please describe the reason why you need to use the npm version bundled with a specific Node.js version, as opposed to using the latest npm version (or alternatively, whichever npm version is locally available)?

Having npm bundled with Node.js was probably a mistake, [according to the creator of Node.js himself](https://youtu.be/M3BM9TB-8yA?t=586). Having those two strongly coupled is unnecessary, users should be able to use whichever version of npm they want, providing that version of npm works on a specific Node.js version (just like any other Node module). `nvexeca` purposely decouples those by only installing Node.js, not npm.

Please note also that `nve` and `nexeca` assumes that the user already has Node.js and npm installed globally. If your use case is to install Node.js and/or npm on a machine which might not have it installed, `nvm`, `nvm-windows`, `n` or `nvs` would probably be a better fit.

**Comment by nicolas-goudry** [comment]
Hi @ehmicky,

Thanks for replying so quickly to this feature request.

I’m currently writing a CLI app which goal is to provide a unified way of launching and managing our Node.js apps internally for development purpose. Some of those apps are ran by multiple npm commands and all apps do not use the same Node version.

Each developper has Node.js installed globally, but as our projects aren’t run against same Node version, use of nvm, n and other tools is becoming a nightmare, that’s why I’m writing this CLI.
For example, our backoffice runs on Node 6, while our front-end is on Node 8 and some of our API on Node 14… You get the point.

I didn’t mention it in the feature request, but what I really need is to be able to run npm scripts that will use a specific Node version, scripts may be `node .` or `gulp watch`. I do not know a way to tell npm to use a specific Node version to run npm scripts. Also, each developper have his habits, some of us use nvm, others use n. Therefore it is not possible to rely on those tools through execa, as there are several to take in account, each with their specificities.

**Comment by nicolas-goudry** [comment]
For now, one workaround I think of :
- parse `package.json`’s scripts to extract command and arguments
- run command through `nvexeca` with path to `node_modules/.bin`

But I’m not really fond of this “solution”.

Exemple:
```js
const pJson = require('/home/me/workspace/myapp/package`)

const scriptsToRun = ['watch', 'dev']
const scripts = scriptsToRun.map((script) => pJson.scripts[script].split(' '))

for (const script in scripts) {
  const [cmd, ...args] = script
  await nvexeca(version, `./node_modules/.bin/${cmd}`, args, { cwd: '/home/me/workspace/myapp' })
}
```
_This is an oversimplified example btw_

**Comment by nicolas-goudry** [comment]
Could it be an option ?

For example : `nvexeca(versionRange, command, args, { ...options, withNpm: true })` ?

Btw, it would ship without npm by default, it would be an opt-in. This means it would need to handle cases where node is in cache without npm.

I’m just wondering how npm would behave if a script just run a shell command… The more I think of this feature, the more questions are raised. In fact, I’m not sure anymore that it would be a good thing to add this feature… Ast it involves handling a lot of special cases.

**Comment by ehmicky** [comment]
> I’m just wondering how npm would behave if a script just run a shell command… The more I think of this feature, the more questions are raised. In fact, I’m not sure anymore that it would be a good thing to add this feature… Ast it involves handling a lot of special cases.

Yes I am coming to similar conclusions. The amount of magic involved in package managers is making me cautious there. See [this function](https://github.com/ehmicky/nvexeca/blob/40cebce8bfa75508630e96ff250c37217f484360/src/spawn.js#L30) for some workarounds `nvexeca` is already doing to accommodate them. And this [whole directory](https://github.com/ehmicky/nvexeca/blob/40cebce8bfa75508630e96ff250c37217f484360/src/copy/main.js#L8) is a hack due to how npm is installing global binaries differently on different platforms. 

Also, if we were to add this feature, the follow-up would be to add Yarn as well. And pnpm.

At a higher-level, I think it might be helpful to think of `npm` as just another Node module. From that angle, your problem could also be described as: different parts of your organization are using different Node.js versions to run the same dependency. In your case, the dependency is `npm`, but other users might run into the same problem with any other dependencies.

If we follow with analogy, if different projects use different Node.js versions, I would expect their `dependencies` to use versions compatible with that Node.js version. The same should apply to their global dependencies (like `npm`).

Did you consider using `nvm`? `nvm install` installs both Node.js and npm. Unless explicitly overridden with `nvm install-latest-npm`, I believe the npm version will be tied to the Node.js version. Each project could have a `.nvmrc` with the proper Node.js version, which would also use the related npm version?

**Comment by nicolas-goudry** [comment]
Sorry, forgot to reply…

I saw the workaround you pointed when going through your code, and I think [n](https://github.com/tj/n) is doing something similar.

As of `yarn` and `pnpm`, I couldn’t agree more! That would really be a nightmare to maintain.

I’m using `n` daily to switch between Node versions, and yes, it seems to also manage `npm` by using most recent compatible version with current Node version.

The whole point of my CLI is to stop using those tools as we do today, because if you work on several projects, you constantly have to `nvm use` or `n` before running! How many times I got errors on run because I forgot to switch Node version… So annoying.

Anyway, I’ll close this issue as I found a workaround that *works* and, as we discussed, in the end it doesn’t seems to be a good idea!

Thanks for your time and btw, great work on `nvexeca` :wink:
